# Generated by Django 5.1.3 on 2025-01-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('idioma', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('qntd_paginas', models.IntegerField()),
                ('classificacao', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('ano_publicacao', models.IntegerField()),
                ('capa', models.ImageField(upload_to='capas/')),
            ],
        ),
    ]
