# Generated by Django 5.1.3 on 2025-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_leitor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfil/'),
        ),
    ]
