# Generated by Django 5.1.3 on 2025-02-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_leitor_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
