# Generated by Django 5.1.3 on 2025-02-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_categoria_alter_livro_categoria'),
        ('user', '0006_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='user.leitor'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='books.livro'),
        ),
    ]
